name: ProjectLea
channels:
  - conda-forge
dependencies:
  - python=3.9.2
  - matplotlib=3.4.1
  - bokeh=2.3.1
  - ipywidgets=7.6.3
  - notebook=6.3.0
  - numpy=1.20.2 
  - pandas=1.2.3
  - pip=21.0.1
  - geopandas=0.9.0
  - scikit-learn=0.24.1

    #  - openpyxl
    #  - scipy 
    #  - seaborn
    #  - xlrd
    #  - lxml
    #  - simplegeneric
    #  - cython

