name: ProjectLea
channels:
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - bokeh
  - ipywidgets
  - notebook
  - numpy
  - pandas
  - pip
  - geopandas
  - scikit-learn

    #  - openpyxl
    #  - scipy 
    #  - seaborn
    #  - xlrd
    #  - lxml
    #  - simplegeneric
    #  - cython

